spring:
    datasource:
        url: ${jdbc.url}
        username: ${jdbc.username}
        password: ${jdbc.password}
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #minIdle: 1
        #maxActive: 2
        #initialSize: 1
        #timeBetweenEvictionRunsMillis: 3000
        #minEvictableIdleTimeMillis: 300000
        #validationQuery: SELECT 'ZTM' FROM DUAL
        #testWhileIdle: true
        #testOnBorrow: false
        #testOnReturn: false

    application:
        name: springBootDemo
        instance_id: clent-one
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: springbus
        password: springbus
mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.springboot.test.domain
springfox:
    api:
        group: group-001
        title: 测试 swagger
        desc: 自动化的在线 api 文档
        version: v2
        termsOfServiceUrl: termsUrl
        contact: jcs7575@gmail.com
        license: licenseSample
        licenseUrl: licenseUrl
#    documentation:
#        swagger:
#            v2:
#                path: apis
eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        healthcheck:
            enabled: true
info:
    app:
        name: ecs
        version: 1.0.0

    build:
        artifactId: @project.artifactId@
        version: @project.version@
endpoints:
    shutdown:
        enabled: true
    restart:
        enabled: true
server:
    port: 8080
ribbon:
    ReadTimeout: 1000
demoservice:
    ribbon:
        DeploymentContextBasedVipAddresses: springBootDemo
        NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
        ReadTimeout: 5000
        MaxAutoRetries: 2

